apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-es-processor-deployment
  labels:
    app: kafka-es-processor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-es-processor
  template:
    metadata:
      labels:
        app: kafka-es-processor
    spec:
      containers:
        - name: kafka-es-processor
          image: your-docker-image:latest
          ports:
            - containerPort: 7001
          env:
            - name: KAFKA_TOPIC
              value: "test_modul_colectare"
            - name: KAFKA_OUTPUT_TOPIC
              value: "modul_colectare_out"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "172.17.12.80:9092"
            - name: ELASTICSEARCH_CERT_PATH
              value: "/app/elastic.crt"
            - name: ELASTICSEARCH_HOST
              value: "https://10.30.11.14:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "elastic"
            - name: ELASTICSEARCH_PASSWORD
              value: "YTrEkQ9G8OzH5rQi1wgK"
            - name: ELASTICSEARCH_INDEX
              value: "modul_colectare"
